# Generated by Django 6.0.4 on 2026-05-18 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('item_type', models.CharField(choices=[('ATTRACTION', 'Attraction'), ('HOTEL', 'Hotel'), ('FLIGHT', 'Flight'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lon', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='api.event')),
            ],
        ),
    ]
