# Generated by Django 6.0.4 on 2026-06-22 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_membership_role_and_more'),
        ('api', '0008_roles_and_role_notification'),
    ]

    operations = [
    ]
