version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1

  frontend:
    build:
      context: ./frontend
    container_name: flutter_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend